/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jFrameCalculator;

/**
 *
 * @author yugal
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     * 
     */
    double num,ans;
    int calculation;
    
   
    public Calculator() {
        initComponents();
        jRadioButton1.setEnabled(false);
    }
    
     public void arithmetic_operation(){
      switch (calculation)
         {
          case 1: //Addition
              ans = num + Double.parseDouble(Txt1.getText());
              Txt1.setText(Double.toString(ans));
              break;
          case 2: //Subtraction
              ans = num - Double.parseDouble(Txt1.getText());
              Txt1.setText(Double.toString(ans));
              break;
          case 3: //Multiplication
              ans = num * Double.parseDouble(Txt1.getText());
              Txt1.setText(Double.toString(ans));
              break;
          case 4: //Division
              ans = num / Double.parseDouble(Txt1.getText());
              Txt1.setText(Double.toString(ans));
              break;
         }
     }
    public void enable(){
        jTextField1.setEnabled(true);
         jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(true);
        
        Btnone.setEnabled(true);
        Btntwo.setEnabled(true);
        Btnthree.setEnabled(true);
        Btnfour.setEnabled(true);
        Btnfive.setEnabled(true);
        Btnsix.setEnabled(true);
        Btnseven.setEnabled(true);
        Btneight.setEnabled(true);
        Btnnine.setEnabled(true);
        Btnzero.setEnabled(true);
        Btndot.setEnabled(true);
        Btnclear.setEnabled(true);
        Btnminus.setEnabled(true);
        Btnplus.setEnabled(true);
        Btndivide.setEnabled(true);
        Btnmultiply.setEnabled(true);
        Btnback.setEnabled(true);
        Btnequal.setEnabled(true);
    }
    public void disable()
    {
        Txt1.setEnabled(false);
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(false);
        
        Btnone.setEnabled(false);
        Btntwo.setEnabled(false);
        Btnthree.setEnabled(false);
        Btnfour.setEnabled(false);
        Btnsix.setEnabled(false);
        Btnseven.setEnabled(false);
        Btneight.setEnabled(false);
        Btnnine.setEnabled(false);
        Btnzero.setEnabled(false);
        Btndot.setEnabled(false);
        Btnplus.setEnabled(false);
        Btnminus.setEnabled(false);
        Btnmultiply.setEnabled(false);
        Btndivide.setEnabled(false);
        Btnequal.setEnabled(false);
        Btnfive.setEnabled(false);
        Btnclear.setEnabled(false);
        Btnback.setEnabled(false);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Txt1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        Btnback = new javax.swing.JButton();
        Btnclear = new javax.swing.JButton();
        Btnplus = new javax.swing.JButton();
        Btnseven = new javax.swing.JButton();
        Btnfour = new javax.swing.JButton();
        Btneight = new javax.swing.JButton();
        Btnnine = new javax.swing.JButton();
        Btnminus = new javax.swing.JButton();
        Btnfive = new javax.swing.JButton();
        Btnsix = new javax.swing.JButton();
        Btnmultiply = new javax.swing.JButton();
        Btnone = new javax.swing.JButton();
        Btntwo = new javax.swing.JButton();
        Btnthree = new javax.swing.JButton();
        Btndivide = new javax.swing.JButton();
        Btnzero = new javax.swing.JButton();
        Btndot = new javax.swing.JButton();
        Btnequal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jButton11.setText("C");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setLocation(new java.awt.Point(500, 250));

        Txt1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Txt1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setText("ON");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setText("OFF");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        Btnback.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Btnback.setText("<--");
        Btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnbackActionPerformed(evt);
            }
        });

        Btnclear.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnclear.setText("C");
        Btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnclearActionPerformed(evt);
            }
        });

        Btnplus.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnplus.setText("+");
        Btnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnplusActionPerformed(evt);
            }
        });

        Btnseven.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnseven.setText("7");
        Btnseven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsevenActionPerformed(evt);
            }
        });

        Btnfour.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnfour.setText("4");
        Btnfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnfourActionPerformed(evt);
            }
        });

        Btneight.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btneight.setText("8");
        Btneight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtneightActionPerformed(evt);
            }
        });

        Btnnine.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnnine.setText("9");
        Btnnine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnnineActionPerformed(evt);
            }
        });

        Btnminus.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnminus.setText("-");
        Btnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnminusActionPerformed(evt);
            }
        });

        Btnfive.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnfive.setText("5");
        Btnfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnfiveActionPerformed(evt);
            }
        });

        Btnsix.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnsix.setText("6");
        Btnsix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsixActionPerformed(evt);
            }
        });

        Btnmultiply.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnmultiply.setText("*");
        Btnmultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnmultiplyActionPerformed(evt);
            }
        });

        Btnone.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnone.setText("1");
        Btnone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnoneActionPerformed(evt);
            }
        });

        Btntwo.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btntwo.setText("2");
        Btntwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtntwoActionPerformed(evt);
            }
        });

        Btnthree.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnthree.setText("3");
        Btnthree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnthreeActionPerformed(evt);
            }
        });

        Btndivide.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btndivide.setText("/");
        Btndivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndivideActionPerformed(evt);
            }
        });

        Btnzero.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnzero.setText("0");
        Btnzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnzeroActionPerformed(evt);
            }
        });

        Btndot.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btndot.setText(".");
        Btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndotActionPerformed(evt);
            }
        });

        Btnequal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Btnequal.setText("=");
        Btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnequalActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btnone)
                                .addGap(18, 18, 18)
                                .addComponent(Btntwo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Btnzero)
                                .addGap(18, 18, 18)
                                .addComponent(Btndot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Btnthree)
                                .addGap(18, 18, 18)
                                .addComponent(Btndivide))
                            .addComponent(Btnequal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jRadioButton1)
                                .addComponent(jRadioButton2))
                            .addGap(10, 10, 10)
                            .addComponent(Btnback)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Btnclear)
                            .addGap(12, 12, 12)
                            .addComponent(Btnplus))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Btnseven)
                                .addGap(18, 18, 18)
                                .addComponent(Btneight)
                                .addGap(18, 18, 18)
                                .addComponent(Btnnine)
                                .addGap(18, 18, 18)
                                .addComponent(Btnminus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Btnfour)
                                .addGap(18, 18, 18)
                                .addComponent(Btnfive)
                                .addGap(18, 18, 18)
                                .addComponent(Btnsix)
                                .addGap(18, 18, 18)
                                .addComponent(Btnmultiply))))
                    .addComponent(Txt1))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btnclear)
                            .addComponent(Btnback, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btnplus))
                        .addGap(256, 256, 256))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btnseven)
                            .addComponent(Btneight)
                            .addComponent(Btnnine)
                            .addComponent(Btnminus))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btnfour)
                            .addComponent(Btnfive)
                            .addComponent(Btnsix)
                            .addComponent(Btnmultiply))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btnone)
                            .addComponent(Btntwo)
                            .addComponent(Btnthree)
                            .addComponent(Btndivide))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btnzero)
                            .addComponent(Btndot)
                            .addComponent(Btnequal))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        enable();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void BtnoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnoneActionPerformed
        // TODO add your handling code here:
        Txt1.setText(Txt1.getText()+"1");
    }//GEN-LAST:event_BtnoneActionPerformed

    private void BtntwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtntwoActionPerformed
        // TODO add your handling code here:
        Txt1.setText(Txt1.getText()+"2");
    }//GEN-LAST:event_BtntwoActionPerformed

    private void BtnthreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnthreeActionPerformed
        // TODO add your handling code here:
        Txt1.setText(Txt1.getText()+"3");
    }//GEN-LAST:event_BtnthreeActionPerformed

    private void BtnfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnfourActionPerformed
        // TODO add your handling code here:
        Txt1.setText(Txt1.getText()+"4");
    }//GEN-LAST:event_BtnfourActionPerformed

    private void BtnfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnfiveActionPerformed
        // TODO add your handling code here:
        Txt1.setText(Txt1.getText()+"5");
    }//GEN-LAST:event_BtnfiveActionPerformed

    private void BtnsixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsixActionPerformed
        // TODO add your handling code here:
        Txt1.setText(Txt1.getText()+"6");
    }//GEN-LAST:event_BtnsixActionPerformed

    private void BtnsevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsevenActionPerformed
        // TODO add your handling code here:
        Txt1.setText(Txt1.getText()+"7");
    }//GEN-LAST:event_BtnsevenActionPerformed

    private void BtneightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtneightActionPerformed
        // TODO add your handling code here:
        Txt1.setText(Txt1.getText()+"8");
    }//GEN-LAST:event_BtneightActionPerformed

    private void BtnnineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnnineActionPerformed
        // TODO add your handling code here:
        Txt1.setText(Txt1.getText()+"9");
    }//GEN-LAST:event_BtnnineActionPerformed

    private void BtnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnminusActionPerformed
        // TODO add your handling code here:
//        Txt1.setText(Txt1.getText()+"-");
        num = Double.parseDouble(Txt1.getText());
        calculation = 2;
        Txt1.setText("");
        jLabel1.setText(num+ "-");
    }//GEN-LAST:event_BtnminusActionPerformed

    private void BtnmultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnmultiplyActionPerformed
        // TODO add your handling code here:
//        Txt1.setText(Txt1.getText()+"*");
        num = Double.parseDouble(Txt1.getText());
        calculation = 3;
        Txt1.setText("");
        jLabel1.setText(num+ "*");
    }//GEN-LAST:event_BtnmultiplyActionPerformed

    private void BtndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndivideActionPerformed
        // TODO add your handling code here:
//        Txt1.setText(Txt1.getText()+"/");
        num = Double.parseDouble(Txt1.getText());
        calculation = 4;
        Txt1.setText("");
        jLabel1.setText(num+ "/");
    }//GEN-LAST:event_BtndivideActionPerformed

    private void BtnzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnzeroActionPerformed
        // TODO add your handling code here:
        Txt1.setText(Txt1.getText()+"0");
    }//GEN-LAST:event_BtnzeroActionPerformed

    private void BtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndotActionPerformed
        // TODO add your handling code here:
        Txt1.setText(Txt1.getText()+".");
    }//GEN-LAST:event_BtndotActionPerformed

    private void BtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnplusActionPerformed
        // TODO add your handling code here:
//        Txt1.setText(Txt1.getText()+"+");
        num = Double.parseDouble(Txt1.getText());
        calculation = 1;
        Txt1.setText("");
        jLabel1.setText(num+ "+");
    }//GEN-LAST:event_BtnplusActionPerformed

    private void BtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnclearActionPerformed
        // TODO add your handling code here:
        Txt1.setText("");
    }//GEN-LAST:event_BtnclearActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        disable();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void BtnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnbackActionPerformed
        // TODO add your handling code here:
        int length = Txt1.getText().length();
        int number = Txt1.getText().length()-1;
        String store;
        
        if(length>0){
            StringBuilder back = new StringBuilder (Txt1.getText());
            back.deleteCharAt(number);
            store = back.toString();
            Txt1.setText(store);    
        }
    }//GEN-LAST:event_BtnbackActionPerformed

    private void BtnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnequalActionPerformed
        // TODO add your handling code here:
        arithmetic_operation();
        jLabel1.setText("");
    }//GEN-LAST:event_BtnequalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnback;
    private javax.swing.JButton Btnclear;
    private javax.swing.JButton Btndivide;
    private javax.swing.JButton Btndot;
    private javax.swing.JButton Btneight;
    private javax.swing.JButton Btnequal;
    private javax.swing.JButton Btnfive;
    private javax.swing.JButton Btnfour;
    private javax.swing.JButton Btnminus;
    private javax.swing.JButton Btnmultiply;
    private javax.swing.JButton Btnnine;
    private javax.swing.JButton Btnone;
    private javax.swing.JButton Btnplus;
    private javax.swing.JButton Btnseven;
    private javax.swing.JButton Btnsix;
    private javax.swing.JButton Btnthree;
    private javax.swing.JButton Btntwo;
    private javax.swing.JButton Btnzero;
    private javax.swing.JTextField Txt1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton11;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
